### ISSUE TITLE
when deleting inactive users I get this error if they have posts that have been quoted

### ISSUE THREAD

**Issue by k1epto** [GerB/quotedwhere#1]
[phpBB Debug] PHP Notice: in file [ROOT]/includes/message_parser.php on line 1198: Undefined index: TOO_FEW_CHARS

General Error
SQL ERROR [ mysqli ]

Column 'post_text' cannot be null [1048]

SQL

UPDATE phpbb_posts SET post_text = NULL, post_checksum = 'd41d8cd98f00b204e9800998ecf8427e' WHERE post_id = 2215718

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 997
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/ext/ger/quotedwhere/classes/handler.php
LINE: 255
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/ext/ger/quotedwhere/event/main_listener.php
LINE: 150
CALL: ger\quotedwhere\classes\handler->rename_user_quotes()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 184
CALL: ger\quotedwhere\event\main_listener->anonymize_poster()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 46
CALL: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 62
CALL: Symfony\Component\EventDispatcher\EventDispatcher->dispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 46
CALL: phpbb\event\dispatcher->dispatch()

FILE: [ROOT]/includes/functions_user.php
LINE: 477
CALL: phpbb\event\dispatcher->trigger_event()

FILE: [ROOT]/includes/acp/acp_inactive.php
LINE: 171
CALL: user_delete()

FILE: [ROOT]/includes/functions_module.php
LINE: 676
CALL: acp_inactive->main()

FILE: [ROOT]/adm/index.php
LINE: 82
CALL: p_master->load_active()

**Comment by GerB** [comment]
That indicates an empty result, which is unexpected. I've updated the extension to cope with that.

Further support please at phpBB.com, that keeps things clear for me. Closing this one.
