### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by k1epto** [GerB/quotedwhere#3]
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 67108872 bytes) in /public_html/ext/ger/quotedwhere/classes/handler.php on line 222`

I'm seeing this error in my php error log, can you help?

**Comment by GerB** [comment]
You probably have a large board (or recently deleted a user with a huge amount of posts) with a limited setting of 128 MB max memory. See if you can up the memory limit.

Also, support is provided on phpBB,com preferably.
